### ISSUE TITLE
Error during importing of Library on Mac

### ISSUE THREAD

**Issue by ar0ra1** [colearendt/xlsx#104]
I do see the Java Error but I'm currently not using Java 9. 

> $ ls /Library/Java/JavaVirtualMachines
jdk1.8.0_181.jdk

```
> library(xlsx)
Error: package or namespace load failed for 'xlsx':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found

**Comment by colearendt** [comment]
This looks like an issue starting `rJava`, and specifically your jvm. Does the following work or fail? If so, you will need to work on debugging your Java installation. (my experience has shown this to be painful on mac)
```
library(rJava)
rJava::.jinit()
```

**Comment by ar0ra1** [comment]
``` 
> library(rJava)
Error: package or namespace load failed for 'rJava':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: dyn.load(file, DLLpath = DLLpath, ...)
  error: unable to load shared object '/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so':
  dlopen(/Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so, 6): Library not loaded: /Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/lib/server/libjvm.dylib
  Referenced from: /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rJava/libs/rJava.so
  Reason: image not found
```

**Comment by colearendt** [comment]
@ar0ra1 Apologies for the delay here. The failure of `rJava` means that this is probably not an issue with `xlsx`. Admittedly, debugging `rJava` issues can be a bit of a pain. If you need help debugging, I would recommend starting a thread on community.rstudio.com , so other users can assist your debugging process!

Essentially, it looks like something is broken in your java or rJava installation. I would aim first at getting `java` working on the command line, then work on getting `rJava` working from R. At that point, the `xlsx` package should work!
