### ISSUE TITLE
Mac home directory not supported in write.xlsx

### ISSUE THREAD

**Issue by engineerchange** [colearendt/xlsx#108]
On Mac OS, 

> read.xlsx("~/...")

 is supported, but 

> write.xlsx("~/...")

 is not supported. Leads to some confusion in workflow.

StackOverflow:
https://stackoverflow.com/questions/23634066/write-xlsx-function-gives-error-when-defining-path-with-the-file-name-but-read-x

**Comment by colearendt** [comment]
Thanks for the report! I have not reproduced yet, but in `loadWorkbook` (used in `read.xlsx` and in one path for `write.xlsx`), we are using `path.expand`, which will expand the home directory to its actual path. 
https://github.com/dragua/xlsx/blob/a91027c0e66835b778a8daa3d4ce5fea3168e6aa/R/Workbook.R#L37

I expect we are not doing so in the path you are using in `write.xlsx`, so we will have to add it in! Honestly, I am partial to the `fs` package that handles stuff like this quite cleanly.
