### ISSUE TITLE
Package makes R crash on macOS with Java 12

### ISSUE THREAD

**Issue by luispuerto** [colearendt/xlsx#126]
I can't build it also because it crashes when it tries to load after building. 

https://gist.github.com/luispuerto/fe653e45f95f1e24c3ec5f30c8d5350d

**Comment by ThomasPepperz** [comment]
Me too. RStudio aborts whenever I execute ```library(xlsx)```

**Comment by colearendt** [comment]
Does the following crash as well? This helps determine if the crash is specifically `xlsx` related or related to `rJava`

```
library("rJava")
.jinit()
```

**Comment by luispuerto** [comment]
yes it does!

**Comment by colearendt** [comment]
Thanks for the quick update! It might be worth taking the request upstream to https://github.com/s-u/rJava , since `xlsx` cannot function without `rJava` working properly. Seg faults are no fun!

**Comment by luispuerto** [comment]
It seem that it's a java bug. So the best practice is to stick to java 11 for a while.

**Comment by colearendt** [comment]
Good to know! Thanks for the update! We'll leave it open for a while in case others are searching for the issue.

**Comment by colearendt** [comment]
Closing this (I forgot about it)! Thanks y'all!
