### ISSUE TITLE
`library(xlsx)` yields "error: Your java version is 10.0.2.  Need 1.5.0 or higher."

### ISSUE THREAD

**Issue by Kodiologist** [colearendt/xlsx#128]
I'm pretty sure 10.0.2 is higher than 1.5.0.

I'm on Ubuntu 18.04 running R 3.5.1. `packageversion("rJava")` is 0.9.10.

**Comment by colearendt** [comment]
@Kodiologist Can you check this with the dev version of `xlsx`? `devtools::install_github("colearendt/xlsx")`. We put in a fix that should hopefully resolve

**Comment by Kodiologist** [comment]
Installation with `install_github` seems to have succeeded, but `library(xlsx)` produces the same error.

**Comment by colearendt** [comment]
Did you restart your R session? If you can do that and then execute `packageVersion("xlsx")`, you should get `0.6.1.9000`

**Comment by Kodiologist** [comment]
Hmm, I've tried restarting. I also removed the package, verified that `library(xlsx)` produced `Error in library(xlsx) : there is no package called ‘xlsx’`, did `devtools::install_github("colearendt/xlsx")`, and launched R again. But `packageVersion("xlsx")` is still 0.6.1 and `library(xlsx)` still says `error: Your java version is 10.0.2.  Need 1.5.0 or higher.`

**Comment by colearendt** [comment]
Oops. I'm sorry! I forgot that this repo still uses `develop` as its main branch. Try `devtools::install_github("colearendt/xlsx@develop")` or `devtools::install_github("colearendt/xlsx", "develop")`.

I need to switch the main branch to being `master` - just haven't gotten to it yet 😬 Thanks for doing the extra work to sanity check!

**Comment by Kodiologist** [comment]
Thanks, that works.

**Comment by colearendt** [comment]
Glad to hear it! Please let me know if I can help with anything else!
