### ISSUE TITLE
Version of Java is detected as higher but still cannot use it

### ISSUE THREAD

**Issue by llrs** [colearendt/xlsx#132]
I don't seem to be able to work with xlsx package even after installing rJava successfully:

``` r
library("rJava")
library("xlsx")
traceback()
#> Error: package or namespace load failed for 'xlsx':
#>  .onLoad failed in loadNamespace() for 'xlsx', details:
#>   call: fun(libname, pkgname)
#>   error: Your java version is 11.0.3.  Need 1.5.0 or higher.
#> No traceback available
```

<sup>Created on 2019-07-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem seems with the following line. That evaluates to 1 on interactive session but to something else when used on the `.onLoad` function:

```
utils::compareVersion("11.0.3","1.5.0")
```
Might be related to #103 and #118 but I see "LC_COLLATE=en_US.UTF-8" on my interactive Rstudio session

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ──────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.0 (2019-04-26)
#>  os       Ubuntu 18.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Madrid               
#>  date     2019-07-01                  
#> 
#> ─ Packages ──────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.0)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  callr         3.2.0   2019-03-15 [1] CRAN (R 3.6.0)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.6.0)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.0)
#>  devtools      2.0.2   2019-04-08 [1] CRAN (R 3.6.0)
#>  digest        0.6.19  2019-05-20 [1] CRAN (R 3.6.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.0)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.6.0)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.6.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.0)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.6.0)
#>  knitr         1.23    2019-05-18 [1] CRAN (R 3.6.0)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.0)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.0)
#>  pkgbuild      1.0.3   2019-03-20 [1] CRAN (R 3.6.0)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.0)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.6.0)
#>  processx      3.3.1   2019-05-08 [1] CRAN (R 3.6.0)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.6.0)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.6.0)
#>  Rcpp          1.0.1   2019-03-17 [1] CRAN (R 3.6.0)
#>  remotes       2.0.4   2019-04-10 [1] CRAN (R 3.6.0)
#>  rJava       * 0.9-11  2019-03-29 [3] CRAN (R 3.5.3)
#>  rlang         0.3.4   2019-04-07 [1] CRAN (R 3.6.0)
#>  rmarkdown     1.13    2019-05-22 [1] CRAN (R 3.6.0)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.0)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.0)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.6.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.6.0)
#>  testthat      2.1.1   2019-04-23 [1] CRAN (R 3.6.0)
#>  usethis       1.5.0   2019-04-07 [1] CRAN (R 3.6.0)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.0)
#>  xfun          0.7     2019-05-14 [1] CRAN (R 3.6.0)
#>  xlsxjars      0.6.1   2014-08-22 [1] CRAN (R 3.6.0)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.6.0)
#> 
#> [1] /home/lrevilla/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by colearendt** [comment]
Yes, this is fixed in the dev version. Sorry for the trouble. Please try `devtools::install_github("colearendt/xlsx@develop")` and see if that resolves. 

Duplicate of #128

**Comment by llrs** [comment]
Worked, thanks for the support and sorry for opening a duplicated issue I didn't find it when I searched for similar issues.

**Comment by colearendt** [comment]
No worries! 😄 Glad I could help! I just need to get in gear and actually release the fix!

**Comment by tsukiikram2** [comment]
i got the same problem 
>library("xlsx")
Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'xlsx', details:
  call: fun(libname, pkgname)
  error: Your java version is 14.  Need 1.5.0 or higher.

i tried  devtools::install_github("colearendt/xlsx@develop") but i got the error :
Error: package or namespace load failed for 'xlsx':
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'C:/Users/tsuki/OneDrive/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
  LoadLibrary failure:  %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/Users/tsuki/OneDrive/Documents/R/win-library/3.6/xlsx'
* restoring previous 'C:/Users/tsuki/OneDrive/Documents/R/win-library/3.6/xlsx'
Error: Failed to install 'xlsx' from GitHub:
  (converted from warning) installation of package ‘C:/Users/tsuki/AppData/Local/Temp/RtmpopdswQ/file2b0c70206b11/xlsx_0.6.1.9000.tar.gz’ had non-zero exit status
Can I have some help

**Comment by colearendt** [comment]
What happens if you try to install from master? Do you get the same failure?

Sent from my iPhone

On Apr 7, 2020, at 3:33 PM, tsukiikram2 <notifications@github.com> wrote:

﻿

i got the same problem

library("xlsx")
Error: package or namespace load failed for ‘xlsx’:
.onLoad failed in loadNamespace() for 'xlsx', details:
call: fun(libname, pkgname)
error: Your java version is 14. Need 1.5.0 or higher.

i tried devtools::install_github("colearendt/xlsx@develop") but i got the error :
Error: package or namespace load failed for 'xlsx':
.onLoad failed in loadNamespace() for 'rJava', details:
call: inDL(x, as.logical(local), as.logical(now), ...)
error: unable to load shared object 'C:/Users/tsuki/OneDrive/Documents/R/win-library/3.6/rJava/libs/i386/rJava.dll':
LoadLibrary failure: %1 is not a valid Win32 application.

Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'

  *   removing 'C:/Users/tsuki/OneDrive/Documents/R/win-library/3.6/xlsx'
  *   restoring previous 'C:/Users/tsuki/OneDrive/Documents/R/win-library/3.6/xlsx'
Error: Failed to install 'xlsx' from GitHub:
(converted from warning) installation of package ‘C:/Users/tsuki/AppData/Local/Temp/RtmpopdswQ/file2b0c70206b11/xlsx_0.6.1.9000.tar.gz’ had non-zero exit status
Can I have some help

**Comment by hyeondori** [comment]
I got the same Error in R.

I think I have the same problem as mentioned above.

library("xlsx")
Error: package or namespace load failed for ‘xlsx’:
.onLoad failed in loadNamespace() for 'xlsx', details:
call: fun(libname, pkgname)
error: Your java version is 14. Need 1.5.0 or higher.

I already try to install from master, but it came out again.

Could you help me?
