### ISSUE TITLE
Bug in addDataFrame

### ISSUE THREAD

**Issue by kitergame123** [colearendt/xlsx#133]
Hi Dev,

Good day to you. Thank you very much for developing this package to ease us for reading and writing excel file using R. However, I found a bug in the function addDataFrame.
```
aux <- as.character(x[,j])
      haveNA <- is.na(aux)
      if (any(haveNA))
        aux[haveNA] <- characterNA

      # Excel max cell size limit 
      if (max(nchar(aux)) > .EXCEL_LIMIT_MAX_CHARS_IN_CELL) {
          warning(sprintf("Some cells exceed Excel's limit of %d characters and they will be truncated", 
                          .EXCEL_LIMIT_MAX_CHARS_IN_CELL))
          aux <- strtrim(aux, .EXCEL_LIMIT_MAX_CHARS_IN_CELL)   
      }
    }
```
The code will replace NA for **aux[haveNA]** if I set characterNA = NA due to I want to output a completely blank cell to Excel for those NA cell instead of "".

However, **max(nchar(aux))** will return NA and resulted **if (max(nchar(aux)) > .EXCEL_LIMIT_MAX_CHARS_IN_CELL)** return an error where value TRUE/FALSE is needed.

Currently I am not able to update the package to 0.6.1 and still using 0.5.7 due to the mentioned issue.

Regards,
ZH Yin

**Comment by colearendt** [comment]
Thanks so much for the report! We will aim to fix this in our next release.
