### ISSUE TITLE
ERROR when writing a list of data frames 

### ISSUE THREAD

**Issue by samuel-rosa** [colearendt/xlsx#153]
My package __febr__ depends on __xlsx__. Today I was testing my package using `devtools::check`. While testing the following example:

```r
dts <-
  febr::febr(dataset = "ctb0013",
             variable = "all",
             merge = TRUE,
             progress = FALSE, verbose = FALSE)
febr2xlsx(x = dts, file = tempfile(fileext = ".xlsx"))
```

I got the following error:

```
Error in if (is.na(value)) { : argument is of length zero
Called from: (function (cell, value, richTextString = FALSE, showNA = TRUE) 
{
    if (is.na(value)) {
        if (showNA) {
            return(invisible(.jcall(cell, "V", "setCellErrorValue", 
                .jbyte(42))))
        }
        else {
            return(invisible())
        }
    }
    value <- switch(class(value)[1], integer = as.numeric(value), 
        numeric = value, Date = as.numeric(value) + 25569, POSIXct = as.numeric(value)/86400 + 
            25569, as.character(value))
    if (richTextString) 
        value <- .jnew("org/apache/poi/sf/usermodel/RichTextString", 
            as.character(value))
    invisible(.jcall(cell, "V", "setCellValue", value))
})(dots[[1L]][[24L]], dots[[2L]][[24L]], dots[[3L]][[1L]], dots[[4L]][[1L]])
```

Any hints?

**Comment by colearendt** [comment]
Very strange!! I'm sorry to hear that! This looks to me like one of the recent changes in `write.xlsx`  may have clashed with the nature of your data structure 😞 Either that or your data structure has changed. I tried very hard to maintain backwards compatibility, but it seems that a `NULL` value is getting passed to `xlsx::setCellValue()` by the `xlsx::write.xlsx()` command in `xlsx::feb2xlsx`. 

Is it possible to share more information about the dataset that you are writing here? I cannot reproduce the issue b/c the `febr` API seems to require authentication.

https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/

Another thing you might try is using `openxlsx::write.xlsx()`. There may be minor differences in implementation, but that package has the advantage of not requiring Java if it meets your needs, which seem pretty straightforward.

I would love to be sure that this issue does not affect others, even if you switch to a different package though! So if you can share more about your dataset, that would be great!

**Comment by samuel-rosa** [comment]
Indeed this is very strange. I now am runing CRAN tests in another machine and got new errors (not related to `xlsx`). However, I only get the errors during the tests with `devtools::check`. Everything runs smoothly outside CRAN tests.

I will run more tests and let you know how it goes.

I will look into `openxlsx::write.xlsx()`.

**Comment by colearendt** [comment]
Apologies for the strangeness! Definitely let me know if there is anything we can help with! Without a better reproducible example, it will be difficult to diagnose any issues from this end. I did run `revdepcheck()` on all CRAN reverse dependencies before releasing and didn't see any issues, unfortunately.

```
> revdepcheck::revdep_details(revdep = "febr")
══ Reverse dependency check ═══════════════════════════════════════════════════════════════════ febr 1.0.3 ══

Status: OK

── Before ───────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✔ | 0 warnings ✔ | 0 notes ✔

── After ────────────────────────────────────────────────────────────────────────────────────────────────────
0 errors ✔ | 0 warnings ✔ | 0 notes ✔
```

**Comment by samuel-rosa** [comment]
You can ignore this error. I could not reproduce it anymore after I updated __devtools__. Sorry for the trouble.

**Comment by colearendt** [comment]
No worries at all!! Always better to have a false positive than an actual bug 😄
