### ISSUE TITLE
xlsx package loading failed with java version 14

### ISSUE THREAD

**Issue by horasm** [colearendt/xlsx#154]
I have recently updated R and Java in my computer and now the "xlsx" package won't load into R. I keep getting the following error message, which seems a little counterintuitive:

Error: package or namespace load failed for ‘xlsx’:
 .onLoad failed in loadNamespace() for 'xlsx', details:
  call: fun(libname, pkgname)
  error: Your java version is 14.  Need 1.5.0 or higher.

My R version is 3.6.3 and my java versions are: 
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)

All the other related packaged work completely fine: rJava and xlsxjars

Any help would be much appreciated!

**Comment by colearendt** [comment]
Sorry for the trouble here!! This looks a lot like the weird Java build number here is causing trouble `14+36-1461`... I have never seen a build number like that... I think at this point our version check causes more trouble than it's worth... maybe we just remove it 😬 

Do you mind sharing which version of `xlsx` you are using? `packageVersion("xlsx")`?

**Comment by horasm** [comment]
Hi,
Thanks for your reply.
I ended up removing Java 14 and installing an older version, java 8, and now it all works fine again.
I just checked and the package version of "xlsx" is 0.6.3.

**Comment by luispuerto** [comment]
Same issue here!

**Comment by colearendt** [comment]
If y'all want to try with `remotes::install_github("colearendt/xlsx@remove-version-check")`, hopefully that should get you past this. I'm considering removing the version check wholesale, since Java 1.5 is _looooong_ gone, and we have had nothing but trouble trying to compare Java versions.

**Comment by luispuerto** [comment]
for me it's working!

**Comment by colearendt** [comment]
Good to hear! I'll merge it - please let me know if you encounter any further difficulties!
