### ISSUE TITLE
Writing xlsx causes extra numbered column to be added to the data

### ISSUE THREAD

**Issue by alapo** [colearendt/xlsx#165]
I have been using `xlsx` because I have a series of data.frames that need to be saved as sheets in a `xlsx` file. The scripts works great but an extra column, that is not present in my original data.frame gets saved. Below is an image and reprex

![img](https://i.imgur.com/E8IdAAw.png)

```{r}
    df <- iris
    xlsx::write.xlsx2(df, "data/Test.xlsx", sheetName = "SheetNumber1", append = TRUE) # uses the xlsx package
```

**Comment by colearendt** [comment]
Apologies for the delay in responding here! This is being added by what is called "row names" on an R data.frame. If you want to remove it, you should use the `row.names` argument.

```
df <- iris
xlsx::write.xlsx2(df, "test.xlsx", row.names = FALSE, sheetName = "SheetNumber1", append = TRUE) # uses the xlsx package
```

There is also an `addDataFrame` function that gives you a bit more granular control over this process. Thanks!
