### ISSUE TITLE
package ‘xls’ is not available (for R version 4.0.2)

### ISSUE THREAD

**Issue by danielcoursera** [colearendt/xlsx#166]
Hello colearendt

today i started a course on R Studio.
The instructor ask us to install your package xlsx

This message appers

> install.packages("xls")
Installing package into ‘C:/Users/user/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘xls’ is not available (for R version 4.0.2)

I have installed 

RStudio
Version 1.3.1056
© 2009-2020 RStudio, PBC

Version 4.0.2 (2020-06-22) -- "Taking Off Again"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

Thanks in advance

**Comment by colearendt** [comment]
Hello @danielcoursera . Thanks for reaching out! Programming languages in general (and R in particular) are very specific about things such as case, spelling, etc. If you notice, the instructor asked you to install the `xlsx` package, and you typed `install.packages("xls")`. 

`install.packages("xlsx")` should work - the problem you are experiencing is a simple typo. The error message you received, `package "xls" is not available` is a message to help explain that problem - the package name you typed does not exist.

I hope that helps! Typically, GitHub is a place better suited for issues with / problems with / proposed improvements to the package, and not user challenges with a given package. For a more free-form discussion oriented around troubleshooting and learning, I would recommend you check out https://community.rstudio.com. 

Keep in mind that in some cases, asking for help on the internet can be a violation of academic honor policies (i.e. if the assignment is an exam, test, or homework assignment that should be completed without assistance), while in other cases it would be highly recommended by the instructor. This seems like the latter to me, but it is always good to keep that in mind! Hope that helps!
