### ISSUE TITLE
append = TRUE does not work

### ISSUE THREAD

**Issue by SaraStg** [colearendt/xlsx#169]
I'm trying to write different data frames in different sheets, using append = TRUE, but it does not work, it just keeps overwriting the first sheet:

For example, this does not work:

write.xlsx(USArrests, file = "myworkbook.xlsx",
      sheetName = "USA-ARRESTS", append = FALSE)
write.xlsx(mtcars, file = "myworkbook.xlsx", 
           sheetName="MTCARS", append=TRUE)
write.xlsx(iris, file = "myworkbook.xlsx",
           sheetName="IRIS", append=TRUE)

**Comment by colearendt** [comment]
@SaraStg thanks for reaching out here, and apologies for your trouble! What version of `xlsx` are you using? Are you using a different package perhaps? A [reprex](https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/) here would be ideal, as there are some other packages with `write.xlsx` functions.

In any case, this seems to be working fine with my testing (using the latest from CRAN as of yesterday). That said, I have not fixed any bugs in this function lately, so I don't think any recent version should have this problem, unless I am misunderstanding.

``` r
library(xlsx)

packageVersion("xlsx")
#> [1] '0.6.4.2'
write.xlsx(USArrests, file = "myworkbook.xlsx",
           sheetName = "USA-ARRESTS", append = FALSE)
write.xlsx(mtcars, file = "myworkbook.xlsx",
           sheetName="MTCARS", append=TRUE)
write.xlsx(iris, file = "myworkbook.xlsx",
           sheetName="IRIS", append=TRUE)

wb <- xlsx::loadWorkbook("myworkbook.xlsx")
getSheets(wb)
#> $`USA-ARRESTS`
#> [1] "Java-Object{Name: /xl/worksheets/sheet1.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml}"
#> 
#> $MTCARS
#> [1] "Java-Object{Name: /xl/worksheets/sheet2.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml}"
#> 
#> $IRIS
#> [1] "Java-Object{Name: /xl/worksheets/sheet3.xml - Content Type: application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml}"

nrow(read.xlsx("myworkbook.xlsx", "MTCARS"))
#> [1] 32
```

<sup>Created on 2020-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SaraStg** [comment]
Dear Cole, thanks a lot for your answer. 
I used the wrong package (openxlsx). With xlsx it works fine. Thanks again for your help!

**Comment by colearendt** [comment]
Glad to hear! Let us know if you run into any more issues! In the future, specifying the package (i.e. `xlsx::write.xlsx`) or examining your search path (with `search()`) can be helpful to see what package you are using!

You can also look at the output of `write.xlsx`, which specifies the namespace.

```
write.xlsx
# ...
<bytecode: 0x7fc38d428338>
<environment: namespace:xlsx>
```
