### ISSUE TITLE
Unable to install - "Rterm.exe - Entry Point Not Found"

### ISSUE THREAD

**Issue by joeschofield0** [colearendt/xlsx#170]
Error message "The procedure entry point EXTPTR_PTR could not be located in the dynamic link library R:\R-4.0.0\library\rJava\lins\x64\rJava.dll"
(I successfully reinstalled rJava and the error persisted).

`> install.packages("xlsx")

  There is a binary version available but the source version is later:
     binary  source needs_compilation
xlsx  0.6.3 0.6.4.2             FALSE

installing the source package ‘xlsx’

trying URL 'https://cran.rstudio.com/src/contrib/xlsx_0.6.4.2.tar.gz'
Content type 'application/x-gzip' length 493019 bytes (481 KB)
downloaded 481 KB

* installing *source* package 'xlsx' ...
** package 'xlsx' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'R:/R-4.0.0/library/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified procedure could not be found.
Execution halted
ERROR: lazy loading failed for package 'xlsx'
* removing 'R:/R-4.0.0/library/xlsx'
Warning in install.packages :
  installation of package ‘xlsx’ had non-zero exit status`

**Comment by colearendt** [comment]
Strange! I am suspicious this is related to our CRAN release yesterday. What happens if you use the binary version provided by CRAN (0.6.3) instead of trying to install the latest from source (a binary has not been built yet)?

The other thing you could try to do is make sure `rJava` is functional: `library(rJava); .jinit()`

**Comment by joeschofield0** [comment]
Thanks for your reply Cole.

> Strange! I am suspicious this is related to our CRAN release yesterday. What happens if you use the binary version provided by CRAN (0.6.3) instead of trying to install the latest from source (a binary has not been built yet)?

I tried `install.packages("https://cran.r-project.org/bin/windows/contrib/4.0/xlsx_0.6.3.zip")` and `...xlsx_0.6.4.2.tar.gz` but got the message _"is not available (for R version 4.0.0)"_


> The other thing you could try to do is make sure rJava is functional: library(rJava); .jinit()
It looks like my problem is with rJava, so I'll go investigate that:

`library(rJava); .jinit()`
Error: package or namespace load failed for ‘rJava’:
 .onLoad failed in loadNamespace() for 'rJava', details:
  call: inDL(x, as.logical(local), as.logical(now), ...)
  error: unable to load shared object 'R:/R-4.0.0/library/rJava/libs/x64/rJava.dll':
  LoadLibrary failure:  The specified procedure could not be found.
In addition: Warning message:
package ‘rJava’ was built under R version 4.0.2
