### ISSUE TITLE
Cannot run the package xlsx for R on my Mac

### ISSUE THREAD

**Issue by marmello77** [colearendt/xlsx#171]
Hello! 

I'm trying to install and load the package **xlsx** in RStudio on my Mac. Sadly, I'm getting this error message:

**_Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
Erro: package or namespace load failed for ‘xlsx’:
 .onLoad falhou em loadNamespace() para 'rJava', detalhes:
  chamada: fun(libname, pkgname)
  erro: JVM could not be found
Além disso: Warning messages:
1: In system("/usr/libexec/java_home", intern = TRUE) :
  execução do comando '/usr/libexec/java_home' teve status 1
2: In fun(libname, pkgname) :
  Cannot find JVM library 'NA/lib/server/libjvm.dylib'
Install Java and/or check JAVA_HOME (if in doubt, do NOT set it, it will be detected)_**

Here are the specs:

_iMac Pro 2017
MacOSX Catalina, 10.15.7

RStudio version 1.3.1073

R version 4.0.2 (2020-06-22)

Java version 8, 261, build 1.8.0_261-b12_

Could you please help me? Thank you in advance!

**Comment by colearendt** [comment]
See this section here: https://github.com/colearendt/xlsx#common-problems

The error message is pretty clear there about what you need to do - Java is not working on your computer. 

> Cannot find JVM library 'NA/lib/server/libjvm.dylib'
> Install Java and/or check JAVA_HOME (if in doubt, do NOT set it, it will be detected)

If you are looking for other packages that do not have the dependency / requirement for Java, then you can use the list here to get started: https://github.com/colearendt/xlsx#issuesmailing-list

I hope that helps! If you need more free-form support, a forum like https://community.rstudio.com might be a better bet. These issues are used to track issues / bugs / feature requests in the package itself.

Thanks! Apologies for the trouble!

**Comment by marmello77** [comment]
Thank you very much!

Java VM is running ok on my Mac, so I assumed it was enough. Now I see other Java is needed.

I'll follow the instructions provided in the first link.
