### ISSUE TITLE
CB.setBorder unexpected behaviour

### ISSUE THREAD

**Issue by paolopavan** [colearendt/xlsx#172]
According to the documentation rowIndex and colIndex are vector so I understand that the following use of `CB.setBorder` should define a rectangular area.
What I get is that is defining a diagonal. Is that expected?
Is there any other shortcut to just having a blank page without formatting?
thanks

```
myblank <- function() {
    Test<- data.frame(a= 10, b=20:80, c=4)
    
    wb<-createWorkbook()
    sheet <- createSheet(wb, "Sheet 1")
    
    allpage <- CellBlock(sheet, 1, 1, 10, 10)
    
    noborder <- Border(color = "white", position = c("BOTTOM", "LEFT", "TOP", "RIGHT"), pen = "BORDER_THIN")
    CB.setBorder(allpage, noborder, rowIndex = c(1:10), colIndex = c(1:10))
    
    saveWorkbook(...)
}
```

**Comment by colearendt** [comment]
Usually if you just want a blank page, you use `BORDER_NONE` (if I am recalling correctly), or just discard styles altogether using something like `addDataFrame()`

``` r
library(xlsx)
wb <- createWorkbook()
s1 <- createSheet(wb)
addDataFrame(mtcars, s1)
saveWorkbook(wb, "/tmp/test.xlsx")
```

<sup>Created on 2022-01-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

That said, I am sure you have moved on to other things 🙈  Apologies for the delay getting back to you here!
