### ISSUE TITLE
Alignment indent

### ISSUE THREAD

**Issue by cat-zeppelin** [colearendt/xlsx#184]
Hello.In Alignment.R the following code (returned value of the 'Alignment' function)
`
structure(list(horizontal=horizontal, vertical=vertical,
wrapText=wrapText, rotation=rotation, indent=0),
class="Alignment")
`
must be changed to
`
structure(list(horizontal=horizontal, vertical=vertical,
wrapText=wrapText, rotation=rotation, indent=indent),
class="Alignment")
`
because it ignores 'indent' from parameters and always returns Alignment object with intent equal to zero.

**Comment by colearendt** [comment]
Good catch, thanks!
