### ISSUE TITLE
Problems writing more than 5 sheets

### ISSUE THREAD

**Issue by KayWilcox** [colearendt/xlsx#201]
I seem to be having problems writing more than 5 sheets to 1 workbook.  The sixth sheet starts as the first sheet and the first five are then deleted (as far as I can tell).  My fix was to write to 3 different workbooks.

**Comment by colearendt** [comment]
Interesting! Thanks for reporting this! This definitely seems like a very strange issue! I know I have done this in the past 😄 

Would it be possible for you to create a reprex of the experience you are seeing? It would make it much easier for me to dig into! Thanks!

https://reprex.tidyverse.org/
