### ISSUE TITLE
colClasses="character" does not seem to work as expected?

### ISSUE THREAD

**Issue by klittle314** [colearendt/xlsx#63]
For a test file, I expect the call
df3 <- read.xlsx("testfile.xlsx",sheetIndex=1,colIndex=c(1:2),endRow=4,colClasses="character")

to produce a data.frame with two columns, each with character values.

Instead, the function call appears to guess at the variable types...

> str(df3)
> 'data.frame':   3 obs. of  2 variables:
>  $ char1: Factor w/ 3 levels "A","B","C": 1 2 3
>  $ num1 : num  1 2 3

Image of Test File (could not get GitHub to accept drag and drop)

![image](https://cloud.githubusercontent.com/assets/3459577/10210827/86167430-67b1-11e5-90af-79b248e355b3.png)

Running R version 3.2.2 on Windows 7, xlsx package 0.5.7, RStudio 0.99.473

thank you, I appreciate the package very much.

**Comment by dragua** [comment]
You need to pass in the stringsAsFactors argument and replicate colClasses. 

df3 <- read.xlsx("testfile.xlsx",sheetIndex=1,colIndex=c(1:2),endRow=4, 
   colClasses=rep("character", 2), 
   stringsAsFactors=FALSE)

not really an issue, more like a question.  You should use the mailing list. 
http://groups.google.com/group/R-package-xlsx

Adrian

**Comment by klittle314** [comment]
OK, thanks for clarification and answer!.

k
