### ISSUE TITLE
autoSizeColumn does not work on RStudio Server

### ISSUE THREAD

**Issue by djhurio** [colearendt/xlsx#66]
I have a problem with using the function `autoSizeColumn` on RStudio Server. It works on RStudio Desktop version, but it fails with an error on RStudio Server. See the example.

``` r
df <- data.frame(matrix(1:100,nc=10))
library(xlsx)
# must save as an xls or xlsx file...
write.xlsx(df,"Final.xlsx", row.names=FALSE)
# load it back
wb <- loadWorkbook("Final.xlsx")
sheets <- getSheets(wb)
# set widths to 20
setColumnWidth(sheets[[1]], colIndex=1:ncol(df), colWidth=20)
saveWorkbook(wb,"Final.xlsx")
# autosize column widths
autoSizeColumn(sheets[[1]], colIndex=1:ncol(df))
saveWorkbook(wb,"Final.xlsx")
```

The first time the error message is:

```
> autoSizeColumn(sheets[[1]], colIndex=1:ncol(df))
Error in .jcall(sheet, "V", "autoSizeColumn", as.integer(ic), TRUE) : 
  java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
```

If I repeat the `autoSizeColumn` I am getting other error:

```
> autoSizeColumn(sheets[[1]], colIndex=1:ncol(df))
Error in .jcall(sheet, "V", "autoSizeColumn", as.integer(ic), TRUE) : 
  java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
```

I have tried two Java versions -- OpenJDK and Oracle Java. Both are resulting with the same error. By the way `setColumnWidth` is working fine.

RStudio Server is running on CentOS release 6.7 (Final). I get the same error if I run it from the terminal.

**Comment by aaiezza** [comment]
I also am experiencing this same issue. I'm thinking it might have something to do with the CLASSPATH variable through the RStudio Server?

**Comment by aaiezza** [comment]
This is more of a workaround, but setting your DISPLAY variable to nothing works out.
`$ export DISPLAY=`
[Can be seen here](http://stackoverflow.com/a/21930692/2787584)

This may be able to be closed.

**Comment by Mohamed-0-Hassan** [comment]
Any update on this issue ?

**Comment by colearendt** [comment]
The issue mentioned here:
```
Error in .jcall(sheet, "V", "autoSizeColumn", as.integer(ic), TRUE) : 
  java.awt.AWTError: Can't connect to X11 window server using ':0' as the value of the DISPLAY variable.
```

is definitely a result of the `DISPLAY` environment variable, and a common issue even outside of the `xlsx` package (it crops up in many contexts even outside of Java). The solution from within an R session is definitely to unset the `DISPLAY` variable:
```
Sys.unsetenv("DISPLAY")
```

That should fix your issue! I would defer to @aaiezza 's link: http://stackoverflow.com/a/21930692/2787584 

The other issue could be the same issue or could be related to either `CLASSPATH` or `JAVA_HOME` (which we discuss in the README at https://github.com/colearendt/xlsx). If you are experiencing an issue, please file a new issue with a [reprex](https://www.jessemaegan.com/post/so-you-ve-been-asked-to-make-a-reprex/) if possible.
